### ISSUE TITLE
Add option to download adminer theme

### ISSUE THREAD

**Issue by anthony-robin** [geerlingguy/ansible-role-adminer#5]
It could also be a good idea to add task to download an adminer theme. When looking at the documentation they are all hosted in the same place with a different template name.

At task like this should be easy to add to your existing recipe:

``` yaml
- vars:
  adminer_theme: "pappu687" # could be "hever", "nette", "brave", ... 
```

``` yaml
- name: "Download adminer {{ adminer_theme }} theme"
  get_url:
    url: https://raw.githubusercontent.com/vrana/adminer/master/designs/{{ adminer_theme }}/adminer.css
    dest: "{{ adminer_install_dir }}"
    mode: 0644
```

Thanks !
